# Generated by Django 3.2 on 2021-04-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('p', 'Person')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('reference', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heidegger_index.lemma')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heidegger_index.work')),
            ],
        ),
    ]
