# Generated by Django 4.0 on 2021-12-27 09:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('p', 'person'), ('w', 'work')], max_length=1, null=True)),
                ('sort_key', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['sort_key'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('csl_json', models.JSONField()),
                ('reference', models.CharField(max_length=200, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField(null=True)),
                ('suffix', models.CharField(choices=[('f', 'And next page'), ('ff', 'And next pages')], max_length=2, null=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heidegger_index.lemma')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heidegger_index.work')),
            ],
            options={
                'ordering': ['lemma', 'work', 'start', 'end', 'suffix'],
            },
        ),
    ]
