# Generated by Django 4.0.1 on 2022-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
