# Generated by Django 3.2 on 2021-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='type',
            field=models.CharField(choices=[('p', 'person'), ('w', 'work')], max_length=1, null=True),
        ),
    ]
