# Generated by Django 4.0.1 on 2022-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0002_lemma_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='sort_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
