# Generated by Django 3.2 on 2021-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0002_lemma_type_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
