# Generated by Django 3.2 on 2021-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0003_work_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagereference',
            name='value',
        ),
        migrations.AddField(
            model_name='pagereference',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagereference',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagereference',
            name='suffix',
            field=models.CharField(choices=[('f', 'And next page'), ('ff', 'And next pages')], max_length=2, null=True),
        ),
    ]
