# Generated by Django 4.0.4 on 2022-05-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0003_alter_lemma_sort_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='heidegger_index.lemma'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='heidegger_index.lemma'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='related',
            field=models.ManyToManyField(to='heidegger_index.lemma'),
        ),
        migrations.AddField(
            model_name='pagereference',
            name='type',
            field=models.CharField(choices=[('r', 'related')], max_length=1, null=True),
        ),
    ]
