# Generated by Django 4.0.4 on 2022-06-23 08:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0005_lemma_first_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['key']},
        ),
        migrations.AddField(
            model_name='work',
            name='key',
            field=models.CharField(default=None, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='heidegger_index.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='key'),
        ),
    ]
