# Generated by Django 4.1 on 2022-08-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0006_work_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='urn',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
