# Generated by Django 4.1 on 2022-08-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0006_work_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='description_md',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='reference_md',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
