# Generated by Django 4.1 on 2023-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0007_lemma_perseus_content_lemma_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='type',
            field=models.CharField(choices=[('p', 'person'), ('w', 'work'), ('g', 'geographical place name')], max_length=1, null=True),
        ),
    ]
