# Generated by Django 4.1 on 2022-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0007_lemma_perseus_content_lemma_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='gnd_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
