# Generated by Django 4.1 on 2023-01-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0007_lemma_perseus_content_lemma_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
