# Generated by Django 4.1 on 2022-08-23 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0007_lemma_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='urn',
            field=models.UUIDField(default=uuid.uuid5, editable=False, null=True),
        ),
    ]
