# Generated by Django 4.1 on 2022-08-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0007_lemma_description_md_work_reference_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemma',
            name='description_md',
        ),
        migrations.RemoveField(
            model_name='work',
            name='reference_md',
        ),
    ]
