# Generated by Django 4.1 on 2022-10-11 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0008_lemma_gnd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='gnd_id',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(1[\\d]{8,9}[0-9X]$)')]),
        ),
    ]
