# Generated by Django 4.1 on 2023-01-04 17:15

from django.db import migrations, models
import heidegger_index.validators


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0008_alter_lemma_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='gnd_id',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[heidegger_index.validators.validate_gnd]),
        ),
    ]
