# Generated by Django 4.1 on 2023-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0009_lemma_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
