# Generated by Django 4.1 on 2022-12-19 19:53

from django.db import migrations, models
import heidegger_index.validators


class Migration(migrations.Migration):

    dependencies = [
        ('heidegger_index', '0010_alter_lemma_gnd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='gnd_id',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[heidegger_index.validators.validate_gnd]),
        ),
    ]
