# Generated by Django 4.1 on 2023-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heidegger_index", "0010_lemma_dk"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
