# Generated by Django 4.2.4 on 2023-10-14 20:19

from django.db import migrations, models
import heidegger_index.validators


class Migration(migrations.Migration):
    dependencies = [
        ("heidegger_index", "0011_work_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lemma",
            name="zeno",
            field=models.CharField(
                max_length=50,
                null=True,
                unique=True,
                validators=[heidegger_index.validators.validate_zeno],
                verbose_name="Zeno.org ID",
            ),
        ),
    ]
