# Generated by Django 4.2.9 on 2024-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heidegger_index", "0012_lemma_zeno"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagereference",
            name="whole",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pagereference",
            name="start",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="pagereference",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("start__isnull", False), ("whole", False)),
                    ("whole", True),
                    _connector="OR",
                ),
                name="Start must be defined when lemma doesn't refer to the whole work",
            ),
        ),
    ]
