# Generated by Django 4.1 on 2024-02-11 23:08

from django.db import migrations, models
import heidegger_index.validators


class Migration(migrations.Migration):

    dependencies = [
        ("heidegger_index", "0012_lemma_zeno"),
    ]

    operations = [
        migrations.AddField(
            model_name="lemma",
            name="lang",
            field=models.CharField(
                max_length=3,
                null=True,
                validators=[heidegger_index.validators.validate_iso639_3_lang],
            ),
        ),
    ]
