<<<<<<< HEAD
# Generated by Django 4.1 on 2024-02-11 23:08

from django.db import migrations, models
import heidegger_index.validators


class Migration(migrations.Migration):

=======
# Generated by Django 4.2.9 on 2024-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
>>>>>>> 7ccf3d4 (Add language field to lemmata)
    dependencies = [
        ("heidegger_index", "0012_lemma_zeno"),
    ]

    operations = [
        migrations.AddField(
            model_name="lemma",
            name="lang",
<<<<<<< HEAD
            field=models.CharField(
                max_length=3,
                null=True,
                validators=[heidegger_index.validators.validate_iso639_3_lang],
            ),
=======
            field=models.CharField(max_length=3, null=True),
>>>>>>> 7ccf3d4 (Add language field to lemmata)
        ),
    ]
