# Generated by Django 4.2.9 on 2024-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "heidegger_index",
            "0013_pagereference_whole_alter_pagereference_start_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagereference",
            options={"ordering": ["whole", "lemma", "work", "start", "end", "suffix"]},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"ordering": ["sort_key"]},
        ),
        migrations.AddField(
            model_name="work",
            name="sort_key",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lemma",
            name="sort_key",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
