# Generated by Django 4.1 on 2024-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heidegger_index", "0015_lemma_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lemma",
            name="lang",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
