type: object
description: Index object
additionalProperties:
  type: object
  description: Lemma object
  properties:
    metadata:
      type: object
      description: Metadata object
      properties:
        urn:
          type: string
          pattern: ^urn:cts:([A-Za-z0-9()+,\-.:=@;$_!*']|%[0-9A-Fa-f]{2})+$
          description: CTS URN
        gnd:
          type: string
          pattern: ^1[012]?\d{7}[0-9X]|[47]\d{6}-\d|[1-9]\d{0,7}-[0-9X]|3\d{7}[0-9X]$
          description: Gemeinsame Normdatei identifier
        dk:
          type: integer
          minimum: 1
          description: Diels-Kranz ID
        zeno:
          type: string
          pattern: ^\d{10}[\dX]$
          description: Zeno.org ID
      additionalProperties: False
    references:
      type: object
      description: References object
      uniqueItems: True
      additionalProperties:
        type: array
        description: List of the page_refs
        uniqueItems: True
        items:
          type: object
          properties:
            start:
              type: integer
              minimum: 0
            end:
              type: integer
              minimum: 0
            type:
              type: string
              enum: [r]
            suffix:
              type: string
              enum: [f, ff]
            whole:
              type: boolean
          allOf:
            - if:
                anyOf:
                  - properties:
                      end:
                        type: integer
                  - properties:
                      suffix:
                        type: string
                  - properties:
                      type:
                        const: r
                  - not:
                      properties:
                        whole:
                          const: True
              then:
                required: [start]
          additionalProperties: False
    related:
      type: array
      description: List of related lemmata
      uniqueItems: True
      items:
        type: string
    parent:
      type: string
      description: Parent lemma
    child:
      type: string
      description: Child lemma
    author:
      type: string
      description: Author of work
    type:
      type: string
      description: Lemma type
      enum: [p, w, g]
  additionalProperties: False
  dependentRequired:
    metadata: [type]
    parent: [references]
  allOf:
    - if:
        properties:
          type:
            const: p
      then:
        properties:
          metadata:
            properties:
              dk:
                maximum: 90
