name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'placeholder'
    - name: Adding known hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: ls -a; rsync -ravz "${PWD}/" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SERVER_ROOT_DIR }}
    - name: Update container on server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd ${{ secrets.SERVER_ROOT_DIR }};
          export SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}";
          make update
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
