name: Validation

on:
  push:
    branches: [ main, improved-data-model, 'feature/**' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate_index:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Validate YAML
        uses: brittonhayes/validate-yaml@v0.3.0
        with:
          # Files to validate
          files: index/heidegger-index.yml
          # Path to schema to validate against
          schemaPath: validation/schema.yml
