name: Validation

on:
  push:
    branches-ignore: [ main ]

  workflow_dispatch:

jobs:
  validate_index:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Validate YAML
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'index/heidegger-index.yml'
          schema: 'validation/schema.yml'
